
name: Dependency Review

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high            # block high/critical vulns
          allow-licenses: Apache-2.0, BSD-2-Clause, BSD-3-Clause, MIT, ISC
          deny-licenses: GPL-3.0, AGPL-3.0  # adjust to your policy
          comment-summary-in-pr: true
