name: Build (Next.js + Vitest)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Keep CI node aligned with Firebase Functions/runtime → Node 20
    # (Add a matrix later only if you truly need it.)
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Type check (tsc)
        run: npx tsc --noEmit

      - name: Unit tests (Vitest)
        run: npm test -- --run

      - name: Build Next.js
        env:
          NEXT_TELEMETRY_DISABLED: "1"
        run: npm run build

      # Optional: cache Next incremental artifacts to speed PR builds
      - name: Cache .next/cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: next-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            next-cache-${{ runner.os }}-
