naname: Build (Next.js + TypeScript)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 (matches Firebase Functions runtime)
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Unit tests (Vitest)
        run: npm test -- --run

      - name: Build Next.js
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build

      # Optional: cache Next build artifacts for PR diffs / preview speed
      - name: Cache .next/cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: next-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            next-cache-${{ runner.os }}-
